### PR TITLE
CIVIL-583

### PR DESCRIPTION
**Pull request by walfly**
Better support for newsroom logo image

### CODE REVIEW

**Comment by walfly** [comment]
@picocassette check this on staging and let me know what you think

**Comment by picocassette** [comment]
@walfly I'm not seeing this on staging https://d.pr/i/TCUMNT

**Comment by picocassette** [comment]
@walfly here are a few UI notes and tweaks that would be nice to get in.

Screen Shot 2019-05-01 at 11 28 57 AM

Screen Shot 2019-05-01 at 11 32 44 AM

**Comment by tobek** [comment]
Added ticket to newsroom signup backlog for these btw https://civilmedia.atlassian.net/browse/CIVIL-709

**Pull request merged**
