### PR TITLE
Works with query param

### PR DESCRIPTION
**Pull request by jorgelo**
* Instead of taking in the token as a url param `/verify-token/:token`, we take is as a query param `verify-token?jwt=xxx`

### CODE REVIEW

**Comment by jorgelo** [comment]
@petersng When this is good to go, feel free to merge in right when the email template update goes out. (I don't want to break login / signup for everyone).

**Comment by jorgelo** [comment]
@tobek Just realized that we'll need to do the same for the newsroom signup.

**Comment by petersng** [comment]
@tobek is there an update on the corresponding work for newsroom signup?

**Comment by tobek** [comment]
Dangit haha we used to use query string param and I changed it to match storefront URLs. I can revert my change, will do shortly, and then we can merge it and this PR and #125 all at once.

**Comment by tobek** [comment]
Alright just created #1023 which will handle for newsroom signup.

**Pull request merged**
