### PR TITLE
chore: update Boost copy

### PR DESCRIPTION
**Pull request by sruddy**

### CODE REVIEW

**Comment by sruddy** [comment]
I didn't change `Boost` to `Project Boost` in a couple spots either for design purposes, in the payment flow where Boost is an action, or in shared components where the same info is true of all types of Boosts.

**Comment by dankins** [comment]
:tada: This PR is included in version 4.9.3 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
